### ISSUE TITLE
Youtube Request Error

### ISSUE THREAD

**Issue by Ashu11-A** [fdciabdul/tmuxdcbot#15]
![IMG_20210413_184100](https://user-images.githubusercontent.com/30575805/114630156-54641180-9c90-11eb-9fd8-2bfc2e77fbd4.jpg)
what I do?
Is it that the YouTube API Key is wrong?

**Comment by Ashu11-A** [comment]
I managed to fix the problem was just to update the ytdl-core, with the following commands:

 `npm uninstall ytdl-core-core`
 `npm uninstall ytdl-core-discord`
 `npm install ytdl-core`
 `npm install ytdl-core-discord`

 But another problem arose!  And this one was with the API, which I found easy!
 Youtube Request Error
 Request failed with status code 400

 But now the bot is not outputting sound, it only connects to the voice channel but does not respond to commands

**Comment by fdciabdul** [comment]
yes you will get 400 , the youtube API V3 is no longer available anymore
