### ISSUE TITLE
Cannot find module Discord.js

### ISSUE THREAD

**Issue by Eclypse2D** [fdciabdul/tmuxdcbot#3]
![Screenshot_20200420_170420](https://user-images.githubusercontent.com/46421694/79760640-093b4b00-8329-11ea-9a32-14dc292e55d6.jpg)

**Comment by fdciabdul** [comment]
typ on ur termux 

`npm install discord.js `

**Comment by Aliosmanq** [comment]
![IMG_20200517_064620](https://user-images.githubusercontent.com/65266581/82135323-279e4480-980a-11ea-9f81-3854c74745c5.jpg) npm install discord.js cant work

**Comment by fdciabdul** [comment]
us should install package manually 

or delete package.json and package.lock.json

**Comment by LeManock** [comment]
npm install discord.js

**Comment by Yonle** [comment]
It saysodule no found. Type ```
npm i
```

**Comment by NazwaS** [comment]
Just type
```bash
npm install discord.js
npm install request
npm i
```

And done.
