### ISSUE TITLE
bot cannot detect user in voice

### ISSUE THREAD

**Issue by branfishy** [fdciabdul/tmuxdcbot#6]
why bot no detect me/user if .join/.play?

**Comment by fdciabdul** [comment]
can you send the error in the termux ?

**Comment by branfishy** [comment]
in termux not error like normal, but if .join or .play bot no detect user
in voice channel

**Comment by fdciabdul** [comment]
try to run `npm update` on termux

**Comment by branfishy** [comment]
still same npm update, bot no detect user

**Comment by lolpbu** [comment]
have you tried replacing `message.member.voiceChannel` with `message.member.voice.channel`?
that's what was causing me the same problem

https://github.com/fdciabdul/tmuxdcbot/issues/9#issue-773459345
